//! Bindings to the tree-sitter CEL parser, generated by tree-sitter

use tree_sitter_language::LanguageFn;

extern "C" {
    fn tree_sitter_cel() -> *const ();
}

/// The tree-sitter CEL language
///
/// # Example
///
/// ```
/// let mut parser = tree_sitter::Parser::new();
/// parser.set_language(&tree_sitter::Language::new(tree_sitter_cel::LANGUAGE)).expect("Error loading CEL grammar");
/// let tree = parser.parse("1 + 2", None).unwrap();
/// assert!(!tree.root_node().is_error());
/// ```
pub const LANGUAGE: LanguageFn = unsafe { LanguageFn::from_raw(tree_sitter_cel) };

/// The source of the CEL language grammar.
pub const GRAMMAR: &str = include_str!("../../grammar.js");

/// The node types of the CEL language grammar.
pub const NODE_TYPES: &str = include_str!("../../src/node-types.json");

#[cfg(feature = "highlights")]
/// Syntax highlighting queries for the CEL language.
pub const HIGHLIGHTS_QUERY: &str = include_str!("../../queries/highlights.scm");

#[cfg(feature = "injections")]
/// Language injections for the CEL language.
pub const INJECTIONS_QUERY: &str = include_str!("../../queries/injections.scm");

#[cfg(test)]
mod tests {
    #[test]
    fn test_can_load_grammar() {
        let mut parser = tree_sitter::Parser::new();
        let language = tree_sitter::Language::new(super::LANGUAGE.into());
        assert!(parser.set_language(&language).is_ok());
    }
}
